//export const MONGO_URI =  `mongodb+srv://${process.env.MONGO_USER_NAME}:${process.env.MONGO_USER_PASSWORD}@cluster0.bavoa.mongodb.net/?retryWrites=true&w=majority`
//export const MONGO_URI = `mongodb://mongo:123@localhost:27017/`;
export const MONGO_USER_NAME = '';
export const MONGO_USER_PASSWORD = '';
export const MONGO_URI = `mongodb+srv://${MONGO_USER_NAME}:${MONGO_USER_PASSWORD}@emerald-cluster.qszztjn.mongodb.net/`;
export const AWS_S3_BUCKET = 'emerald-city';
export const AWS_S3_REGION = 'ap-south-1';
export const DB_NAME = 'emerald';
export const AWS_ACCESS_KEY_ID = '';
export const AWS_SECRET_ACCESS_KEY = '';
